### ISSUE TITLE
Typescript build error in 4.31.5

### ISSUE THREAD

**Issue by huineng** [IBM/carbon-components-angular#1661]
this is the error i get in my build using carbon-components-angular 4.31.5

```
ERROR in node_modules/carbon-components-angular/table/carbon-components-angular-
table.d.ts.TableRowComponent.html(56,6): Property 'getItemTitle' does not exist on type 'TableRowComponent'.
```

thanks

**Comment by cal-smith** [comment]
Huh, I'm not sure how this happened ... @zvonimirfras I think this is related the TableItem in https://github.com/IBM/carbon-components-angular/pull/1653

**Comment by huineng** [comment]
yes , it should either be 

```
[title]="item.title"
```

or the function getItemTitle(item) needs to be created

**Comment by cal-smith** [comment]
This appears to be fixed now 🎉
