### ISSUE TITLE
Angular Component dropdown--multi-select Not working properly @3.15.1

### ISSUE THREAD

**Issue by gandradeglez** [IBM/carbon-components-angular#741]
## Title 
Angular Component dropdown--multi-select Not working properly

## Detailed description

When selecting one or more option and then deselecting all of then there is an error:

```
core.js:1671 ERROR TypeError: Cannot read property 'isUpdate' of null
    at dropdown.component.ts:308
    at SafeSubscriber.schedulerFn [as _next] (core.js:3568)
    at SafeSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub (Subscriber.js:194)
    at SafeSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next (Subscriber.js:132)
    at Subscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next (Subscriber.js:76)
    at Subscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (Subscriber.js:53)
    at EventEmitter.push../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next (Subject.js:47)
    at EventEmitter.push../node_modules/@angular/core/fesm5/core.js.EventEmitter.emit (core.js:3540)
    at DropdownList.push../src/dropdown/list/dropdown-list.component.ts.DropdownList.doClick (dropdown-list.component.ts:457)
    at Object.eval [as handleEvent] (VM28 DropdownList.ngfactory.js:56)
```

What browser are you working in?
Google Chrome - Version 76.0.3809.132 (Official Build) (64-bit)
Mozilla Quantum - 68.0.2 (64-bit)

## Steps to reproduce the issue

1. Select one or more option on the drop down
2. Deselect the options by clicking on each of them

## Additional information
![image](https://user-images.githubusercontent.com/55098163/64551510-c3ca9000-d2fa-11e9-8848-dca27b951e78.png)

![image](https://user-images.githubusercontent.com/55098163/64551518-c7f6ad80-d2fa-11e9-8609-b8655717b330.png)

this is happening in my application and also same issue in official documentation demo
https://angular.carbondesignsystem.com/?path=/story/dropdown--multi-select

**Comment by gandradeglez** [comment]
Working with carbon-components-angular@3.15.1

**Comment by cal-smith** [comment]
Awesome, let me know if I need to re-open this

**Comment by gandradeglez** [comment]
> Awesome, let me know if I need to re-open this

Sorry my bad what I wanted to say is I'm working with that version and is not working. Please reopen this

**Comment by gandradeglez** [comment]
> > Working with carbon-components-angular@3.15.1
> 
> We are currently using "carbon-components": "^10.6.1" and "carbon-components-angular": "^3.16.0" and still having the issue.
> 
> `main.47ce0681fe67b85dc362.js:1 ERROR TypeError: Cannot read property 'isUpdate' of null at main.47ce0681fe67b85dc362.js:1 at e.o [as _next] (main.47ce0681fe67b85dc362.js:1) at e.__tryOrUnsub (main.47ce0681fe67b85dc362.js:1) at e.next (main.47ce0681fe67b85dc362.js:1) at e._next (main.47ce0681fe67b85dc362.js:1) at e.next (main.47ce0681fe67b85dc362.js:1) at e.next (main.47ce0681fe67b85dc362.js:1) at e.emit (main.47ce0681fe67b85dc362.js:1) at t.doClick (main.47ce0681fe67b85dc362.js:1) at Object.handleEvent (main.47ce0681fe67b85dc362.js:1)`
> 
> Infact the issue is reproducible even here: [https://angular.carbondesignsystem.com/?path=/story/dropdown--multi-select-with-ngmodel](url)
> 
> Can you please check and reopen this issue?
> 
> Regards,
> Navin

ng-model isn't working properly neither...

**Comment by cal-smith** [comment]
Thanks for the clarification and extra detail 👍 We'll look into this ...

**Comment by cal-smith** [comment]
It does now :+1:
